# 服务端口号 Server port サーバポート
server:
  port: 8080

# 数据库连接配置 Database connection データベース接続構成
spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    # username: root
    # password: root123!
    # Alibaba Druid
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root123!

# 日志 Logs ログ
logging:
  level:
    root: info
    com.northsea: info

# MyBatis Plus 表名前缀 テーブル名のプレフィックス
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


